### ISSUE TITLE
Checklist before first release

### ISSUE THREAD

**Issue by rithviknishad** [Vaidyuti/vems#20]
## Priority P1

- [x] CRUD+LP API endpoints for `prosumer.Prosumer` model.
- [x] CRUD+LP API endpoints for `core.p2p-transactions` model. 
- [x] #23
- [ ] #28
- [ ] #27
Unmet demand shall be applied on a fixed rate purchased from external source / EB.
- [ ] #26

## Priority P2

- [x] Configure heroku
- [x] Automated staging deploys to heroku on `main` branch.
- [ ] #29
- [ ] #30

## Priority P3

- [x] CRUD+LP API endpoints for `prosumer.Generation` model.
- [x] CRUD+LP API endpoints for `prosumer.Load` model.
- [x] CRUD+LP API endpoints for `prosumer.Storage` model.

## Docker Containers
- [x] Configure Postgres and environments.
- [x] Configure EMQX MQTT Server. 
- [x] Configure InfluxDB.
- [x] Configure Telegraf.
- [ ] #31

```yaml
# staging credentials

postgres:
  database: vems
  username: vems
  password: vems

emqx:
  username: admin
  password: public

influxdb:
  username: vaidyuti-admin
  password: Vaidyuti@123
  bucket: vaidyuti-sandbox-1
  organization: vaidyuti
```
